{
 "title": "API-Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path, method, status) (rate(http_request_histogram_bucket{status=\"Internal Server Error\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}-[{{status}}]"
    }
   ]
  },
  {
   "title": "Req / s Per Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count[$__rate_interval])) by (path, method, status)",
     "legendFormat": "{{method}} {{path}}-[{{status}}]"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (path, method, status) (rate(http_request_histogram_bucket[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}-[{{status}}]"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"172.17.0.1:8080\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"172.17.0.1:8080\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"172.17.0.1:8080\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{pod}} - heap inuse" }
   ]
  },
  {
   "title": "Req / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"backend:8080\", job=\"local-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}